language: c
before_install:
  - |
      sudo apt-get install -qq valgrind
script:
  - make
  - make full-test
compiler:
  - cc
  - gcc
  - clang

# safelist
branches:
  only:
    - master
    - develop
