script: make

# blocklist
#branches:
#  except:
#  - legacy
#  - experimental

# safelist
branches:
  only:
  - master

notifications:
  webhooks:
    urls:
#     - https://hooks.slack.com/services/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
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
