language: c
before_install:
  - |
      sudo apt-get install -qq valgrind
  - pip install --user cpp-coveralls
script:
  - make test
  - make leak-test
  - make coverage-test
compiler:
  - cc
  - gcc
  - clang

# safelist
branches:
  only:
    - master
    - develop
