language: c
before_install:
  - |
      sudo apt-get install -qq valgrind
  - pip install --user cpp-coveralls
script:
  - make test
after_success:
  - cpp-coveralls -y .coveralls.yaml
compiler:
  - cc
  - gcc
  - clang

# safelist
branches:
  only:
    - master
    - develop
